# Generated by Django 5.0.3 on 2024-03-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_channel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
